name: food_expiration_tracker_mobile
description: "Smart food expiration tracker mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  camera: ^0.11.1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
